# Collect logs from all Docker containers
filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
          match_source_index: 4

output.logstash:
  hosts: ["logstash:5044"]
